### ISSUE TITLE
Create DirectoryService class to wrap `directory-service` endpoint

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/psu_identity#16]
`directory-service` will provide us with more metadata, specifically OrcIDs, that will be useful for ScholarSphere: https://github.com/psu-libraries/scholarsphere/issues/518 .

FYI `directory-service` requires an API token.

**Comment by whereismyjetpack** [comment]
I have put in another request to EIT to get access to this API so we can noodle around

**Comment by whereismyjetpack** [comment]
Just a thought, instead of using directory-service instead of search-service, we implement a new class `DirectoryService` and wrap it in similar methods that search-service has? might seem a bit duplicative but the gem could house a lot of psu's identity apis?

**Comment by ajkiessl** [comment]
Yeah, I think that's actually how Adam envisioned it.

**Comment by ajkiessl** [comment]
#17
